# Global settings
concurrent_jobs: 1 # Maximum number of jobs to process concurrently. I'm not sure if the average PC would ever be able to handle more than 1.
threads: 8 # Number of threads to use for multithreaded operations
enable_detailed_exceptions: True # Whether to include full tracebacks when the job manager raises exceptions
cleanup: False # Whether to cleanup working directories after processing or retain intermediate data for reruns
depth_processor: "DepthPro" # Which depth processor to use in ["DepthAnythingV2", "DepthPro", "DistillAnyDepth"]
stereo_processor: "StereoVision" # Which stereo processor to use in ["StereoVision"]

# Depth Anything V2 settings
da2_model: "vitb" # Which model to use in ['vits', 'vitb', 'vitl']

# Distill Any Depth settings
dad_model: "vitb" # Which model to use in ['vits', 'vitb', 'vitl']

# StereoVision settings
sv_depth_scale: 200 # Intensity of the depth effect. The original ComfyUI node defaults to 80, but I found that to be really weak.

# Working directories
working_dir: "working"
frames_dir: "frames"
da2_depth_dir: "depths_da2"
dp_depth_dir: "depths_dp"
dad_depth_dir: "depths_dad"
sv_sbs_dir: "frames_sbs_sv"